server:
  port: 8081
spring:
  application:
    name: timetable-service
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable_db
    username: postgres
    password: Informatique94
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 30  # Heartbeat interval (default)
    leaseExpirationDurationInSeconds: 90  # Time before Eureka considers the instance expired (default)